"""Generate docs/tools.md from the live tool registry.

Hand-written tool references drift from the code. This reads the registry and writes
the reference, so the documentation cannot disagree with what the tools actually accept.

    python scripts/gen_tool_reference.py
    python scripts/gen_tool_reference.py --check   # fail if the file is stale
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from winmcp.tools import build_registry  # noqa: E402

OUTPUT = ROOT / "docs" / "tools.md"


def _type_of(prop: dict) -> str:
    t = prop.get("type", "any")
    if t == "array":
        inner = prop.get("items", {}).get("type", "any")
        return f"array<{inner}>"
    return str(t)


def render() -> str:
    reg = build_registry()
    full_tokens = round(reg.schema_chars() / 3.3)

    lines: list[str] = [
        "# Tool reference",
        "",
        "<!-- Generated by scripts/gen_tool_reference.py — do not edit by hand. -->",
        "",
        f"All {len(reg.names())} tools, generated from the live registry.",
        f"The complete schema set costs approximately **{full_tokens:,} tokens** and is",
        "re-read by the model on every turn.",
        "",
        "Every tool returns `ToolResult(text, data, image_png)`: `text` is for the model,",
        "`data` is structured for programs, and `image_png` carries a screenshot when the",
        "tool captured one.",
        "",
        "## Index",
        "",
        "| Tool | Category | Risk | Params |",
        "|---|---|---|---:|",
    ]

    for t in reg.all():
        anchor = t.name.lower()
        lines.append(
            f"| [`{t.name}`](#{anchor}) | {t.category} | {t.risk.value} | "
            f"{len(t.schema.get('properties', {}))} |"
        )

    lines += ["", "---", ""]

    for t in reg.all():
        props = t.schema.get("properties", {})
        required = set(t.schema.get("required", []))

        lines += [
            f"## {t.name}",
            "",
            f"*{t.category}* · risk **{t.risk.value}**",
            "",
            t.description,
            "",
        ]

        if props:
            lines += ["| Parameter | Type | Required | Description |", "|---|---|---|---|"]
            for name, spec in props.items():
                req = "yes" if name in required else ""
                desc = (spec.get("description") or "").replace("|", "\\|")
                lines.append(f"| `{name}` | `{_type_of(spec)}` | {req} | {desc} |")
            lines.append("")
        else:
            lines += ["Takes no parameters.", ""]

        lines += [
            "<details><summary>JSON schema</summary>",
            "",
            "```json",
            json.dumps(t.schema, ensure_ascii=False, indent=2),
            "```",
            "",
            "</details>",
            "",
        ]

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description="generate the tool reference")
    ap.add_argument("--check", action="store_true", help="fail if the file is out of date")
    args = ap.parse_args()

    content = render()
    if args.check:
        existing = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if existing != content:
            print(f"{OUTPUT} is out of date — run scripts/gen_tool_reference.py")
            return 1
        print(f"{OUTPUT} is up to date")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUTPUT} ({len(content):,} chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
